#!/usr/bin/env node
/* SAMEINA TVÍSKRÁÐAN STAÐ — færir allt af tvítakinu yfir á þann sem stendur.
 *
 * ⛔ STANDANDI REGLA: staði rekstrarfélags má ALDREI sameina. Þetta tól er
 * aðeins fyrir tilvik þar sem Agnar hefur STAÐFEST að um TVÍSKRÁNINGU sé að
 * ræða — sama hús skráð tvisvar — ekki tvo aðskilda staði sama félags.
 * Miðleiti 2-6 (húsfélag + bílageymsla) er dæmi um það sem má EKKI sameina.
 *
 * HVAÐ ÞAÐ GERIR
 *   1. Tæki tvítaksins er EYTT, ekki flutt. `uttaeki` er TELJARI (Agnar
 *      01.09.2026: „tækjanúmer skipta engu máli, autogenerated til að matcha
 *      tríóið"). Væru þau flutt myndi talan tvöfaldast — 19 + 18 = 37 fyrir hús
 *      sem á 19 tæki. Sá sem stendur heldur sinni tölu og hún á áfram að stemma
 *      við skýrsluna sína.
 *   2. Skjöl eru FÆRÐ, aldrei eytt (§2: `is_duplicate` er afturkræft flagg,
 *      skjali er ALDREI eytt). Eigi sá sem stendur þegar skjal af sömu tegund og
 *      ári fær aðflutta skjalið `is_duplicate=true` + `dup_of` á það sem fyrir er.
 *   3. `arsskodun_report_facts` tvítaksins er eytt — sá sem stendur ber réttu
 *      skýrslutöluna og talan er PK per stað.
 *   4. Fyrirtækið sjálft er MJÚK-eytt (`deleted_at`), aldrei hart.
 *   5. Sannreynt á eftir: tækjafjöldi þess sem stendur == skýrslutalan hans.
 *
 * Afrit af ÖLLU sem snert er fer í tools/bakk-sameining-<dags>-<id>.json áður
 * en nokkuð er skrifað.
 *
 * Keyrsla:
 *   node tools/sameina-stad.cjs <stendur> <tvitak>            (þurrkeyrsla)
 *   node tools/sameina-stad.cjs <stendur> <tvitak> --keyra    (skrifar)
 */
const fs = require('fs');
const path = require('path');

const rot = path.join(__dirname, '..');
const cfg = fs.readFileSync(path.join(rot, 'js/config.js'), 'utf8');
const URL_ = (cfg.match(/SUPABASE_URL\s*=\s*["']([^"']+)/) || [])[1];
const KEY = (cfg.match(/SUPABASE_KEY\s*=\s*["']([^"']+)/) || [])[1];
const H = { apikey: KEY, Authorization: 'Bearer ' + KEY, 'Content-Type': 'application/json' };

const STENDUR = parseInt(process.argv[2], 10);
const TVITAK = parseInt(process.argv[3], 10);
const KEYRA = process.argv.includes('--keyra');

if (!STENDUR || !TVITAK || STENDUR === TVITAK) {
  console.log('Notkun: node tools/sameina-stad.cjs <stendur-fid> <tvitak-fid> [--keyra]');
  process.exit(1);
}

// Öll köll fara hér í gegn svo þögul 400-villa geti ekki litið út eins og
// „ekkert til" — nákvæmlega gildran sem kostaði tíma 01.09.2026.
async function sb(slod, valkostir) {
  const r = await fetch(`${URL_}/rest/v1/${slod}`, { headers: H, ...(valkostir || {}) });
  if (!r.ok) throw new Error(`${(valkostir && valkostir.method) || 'GET'} ${slod.slice(0, 60)} → ${r.status} ${(await r.text()).slice(0, 200)}`);
  const t = await r.text();
  return t ? JSON.parse(t) : [];
}

(async () => {
  const [a] = await sb(`fyrirtaeki?select=*&id=eq.${STENDUR}`);
  const [b] = await sb(`fyrirtaeki?select=*&id=eq.${TVITAK}`);
  if (!a) throw new Error(`fyrirtaeki ${STENDUR} finnst ekki`);
  if (!b) throw new Error(`fyrirtaeki ${TVITAK} finnst ekki`);
  if (b.deleted_at) throw new Error(`fyrirtaeki ${TVITAK} er þegar mjúk-eytt (${b.deleted_at})`);

  const kt = s => String(s || '').replace(/\D/g, '');
  if (kt(a.kennitala) !== kt(b.kennitala)) {
    console.log(`⚠ ÓLÍKAR KENNITÖLUR — ${a.kennitala} vs ${b.kennitala}.`);
    console.log('  Þetta tól er fyrir tvískráningu SAMA aðila. Stöðvað.');
    process.exitCode = 1; return;
  }

  const [taekiA, taekiB, skjolA, skjolB, rfA, rfB, solurB] = await Promise.all([
    sb(`uttaeki?select=id,type,size,status&fyrirtaeki_id=eq.${STENDUR}&status=neq.urelt`),
    sb(`uttaeki?select=*&fyrirtaeki_id=eq.${TVITAK}`),
    sb(`customer_documents?select=id,doc_type,year,invoice_number,is_duplicate&fyrirtaeki_id=eq.${STENDUR}`),
    sb(`customer_documents?select=*&fyrirtaeki_id=eq.${TVITAK}`),
    sb(`arsskodun_report_facts?select=report_year,total_devices&fyrirtaeki_id=eq.${STENDUR}`),
    sb(`arsskodun_report_facts?select=*&fyrirtaeki_id=eq.${TVITAK}`),
    sb(`solur?select=id,num&customer_id=eq.${TVITAK}`),
  ]);

  console.log(`STENDUR   fid ${STENDUR}  ${a.nafn}`);
  console.log(`          ${taekiA.length} tæki · ${skjolA.length} skjöl · skýrslutala ${rfA.map(x => x.report_year + ':' + x.total_devices).join(',') || '-'}`);
  console.log(`TVÍTAK    fid ${TVITAK}  ${b.nafn}`);
  console.log(`          ${taekiB.filter(x => x.status !== 'urelt').length} tæki (${taekiB.length} m/úreltum) · ${skjolB.length} skjöl · skýrslutala ${rfB.map(x => x.report_year + ':' + x.total_devices).join(',') || '-'}`);
  if (solurB.length) {
    console.log(`\n⛔ TVÍTAKIÐ BER ${solurB.length} SÖLUR (${solurB.map(s => s.num).join(', ')}).`);
    console.log('   Sölur eru fjárhagsgögn og þetta tól færir þær ekki. Stöðvað.');
    process.exitCode = 1; return;
  }

  // hvaða skjöl verða tvítök við flutning
  const lykill = d => d.doc_type + '|' + d.year;
  const fyrir = new Map();
  // Frumrit gengur fyrir: `dup_of` má ALDREI benda á skjal sem er sjálft merkt
  // tvítak — þá verður keðja sem enginn getur rakið aftur að frumritinu.
  skjolA.filter(d => !d.is_duplicate).forEach(d => { const L = lykill(d); if (!fyrir.has(L)) fyrir.set(L, d.id); });
  skjolA.filter(d => d.is_duplicate).forEach(d => { const L = lykill(d); if (!fyrir.has(L)) fyrir.set(L, d.id); });
  const adgerdir = skjolB.map(d => {
    const L = lykill(d);
    return { id: d.id, teg: d.doc_type, ar: d.year, dupAf: fyrir.has(L) ? fyrir.get(L) : null };
  });

  console.log('\nÁÆTLUN');
  console.log(`  · EYÐA ${taekiB.length} uttaeki-röðum af tvítakinu (teljari, ekki skrá — flutningur myndi tvöfalda töluna)`);
  console.log(`  · FÆRA ${adgerdir.length} skjöl á fid ${STENDUR}:`);
  adgerdir.forEach(x => console.log(`      skjal ${String(x.id).padEnd(6)}${x.ar} ${x.teg.padEnd(17)}`
    + (x.dupAf ? `→ is_duplicate, dup_of ${x.dupAf}` : '→ frumrit (sá sem stendur á ekkert slíkt)')));
  if (rfB.length) console.log(`  · EYÐA ${rfB.length} arsskodun_report_facts-röð af tvítakinu`);
  console.log(`  · MJÚK-EYÐA fid ${TVITAK}`);
  console.log(`  · Eftir stendur: ${taekiA.length} tæki, skýrslutala ${rfA.map(x => x.total_devices).join(',') || '-'}`);

  if (!KEYRA) { console.log('\nÞurrkeyrsla — ekkert skrifað. Bættu við --keyra.'); return; }

  const bakk = path.join(__dirname, `bakk-sameining-${new Date().toISOString().slice(0, 10)}-${TVITAK}.json`);
  fs.writeFileSync(bakk, JSON.stringify({ stendur: a, tvitak: b, taekiB, skjolB, rfB }, null, 1), 'utf8');
  console.log(`\nAfrit: ${path.relative(rot, bakk)}`);

  for (const x of adgerdir) {
    await sb(`customer_documents?id=eq.${x.id}`, { method: 'PATCH', body: JSON.stringify(
      Object.assign({ fyrirtaeki_id: STENDUR }, x.dupAf ? { is_duplicate: true, dup_of: x.dupAf } : {})) });
  }
  console.log(`  ✓ ${adgerdir.length} skjöl færð`);

  if (rfB.length) { await sb(`arsskodun_report_facts?fyrirtaeki_id=eq.${TVITAK}`, { method: 'DELETE' }); console.log('  ✓ report_facts eytt'); }
  if (taekiB.length) { await sb(`uttaeki?fyrirtaeki_id=eq.${TVITAK}`, { method: 'DELETE' }); console.log(`  ✓ ${taekiB.length} tæki eytt`); }

  await sb(`fyrirtaeki?id=eq.${TVITAK}`, { method: 'PATCH',
    body: JSON.stringify({ deleted_at: new Date().toISOString(), er_i_thjonustu: false }) });
  console.log(`  ✓ fid ${TVITAK} mjúk-eytt`);

  // ── sannreyn ────────────────────────────────────────────────────────────
  const eftirT = await sb(`uttaeki?select=id&fyrirtaeki_id=eq.${STENDUR}&status=neq.urelt`);
  const eftirRF = await sb(`arsskodun_report_facts?select=total_devices&fyrirtaeki_id=eq.${STENDUR}`);
  const eftirS = await sb(`customer_documents?select=id&fyrirtaeki_id=eq.${STENDUR}`);
  const leif = await sb(`uttaeki?select=id&fyrirtaeki_id=eq.${TVITAK}`);
  const skyrsla = eftirRF.length ? eftirRF[0].total_devices : null;
  console.log(`\nSANNREYN  ${eftirT.length} tæki · ${eftirS.length} skjöl · skýrslutala ${skyrsla == null ? '-' : skyrsla}`
    + `  · leifar á tvítakinu: ${leif.length}`);
  console.log(skyrsla != null && skyrsla === eftirT.length
    ? '✅ Tækjatalan stemmir við skýrsluna — tríóið getur staðfest staðinn.'
    : '⚠ Tækjatalan stemmir EKKI við skýrsluna. Skoðaðu áður en þú treystir henni.');
})().catch(e => { console.log('❌ ' + e.message); process.exitCode = 1; });
