-- 2026-09-11 — krofu_verkferli: framvinda vinnuglugga krafna (patch 369, Þjónustuborð → Kröfur)
--
-- ✅ BEITT 11.09.2026 (migration krofu_verkferli, kaflar 1–4) eftir yfirferð verkefnastjóra.
--    Staðfest: 5 upphafsmál (4 × krafa_ekki_stofnud + solur:454:faera_kt), öll 'opid', saga = 1; RLS kveikt;
--    anon: INSERT,SELECT,UPDATE. Prófað sem anon í afturkallaðri færslu: insert ok, update ok, saga skráði
--    stöðubreytinguna, DELETE → „permission denied". Undanþágan í tools/audit-daudar-siur.cjs tekin út.
--
-- Hvað taflan geymir: EINA röð á mál („solur:454:faera_kt", „fyrirtaeki:1175:gleymt:2026", …).
--   • stada  opid → tilbuid_i_vinnslu (takki Agnars, engar aðrar afleiðingar) → i_vinnslu (Claude)
--            → i_yfirferd_agnars (krafan situr ÓSEND í Kröfuyfirliti) → lokid; eða sleppt.
--   • skref  merkt þrep: { "<þrep>": { gert, af, kl } } og valin leið { "_leid": { v, af, kl } }.
--   • gogn   inntak málsins sem gögnin sjálf geyma ekki: markkt/marknafn (faera_kt), heimild
--            („Krafa stofnuð" = Nei — Payday-spegillinn hefur engan slíkan dálk), upphaflegt
--            (dk_invoice_id, kt, nafn, customer_base_id … fyrir afturköllun, svo hægt sé að sannreyna hana).
--   • saga   stöðubreytingar, skrifaðar af gikknum hér að neðan — viðmótið getur ekki endurskrifað þær.
--   Viðbót við tillögu verkefnisins: fyrirtaeki_id (gleymdar úttektir eiga enga sölu), gogn og saga.
--
-- Aðgangur: sama mynstur og sara_yfirferd / fyrirtaeki_virkni — RLS KVEIKT með opnum reglum fyrir
--   anon/authenticated (appið notar opinbera lykilinn), en ENGIN delete-regla og hvorki DELETE né
--   TRUNCATE leyft: mál er „sleppt", aldrei eytt, svo sagan lifir. Engin realtime-útgáfa (audit-realtime
--   ber RT_TABLES í db.js saman við útgáfuna); 369 les ferskt við hverja opnun.

-- ── 1. Taflan ────────────────────────────────────────────────────────────────────────────
create table if not exists public.krofu_verkferli (
  id               bigint generated by default as identity primary key,
  mal_lykill       text not null unique check (mal_lykill ~ '^(solur|fyrirtaeki|annad):'),
  tegund           text not null check (tegund in ('itreka','senda_krofu','payday_drog','krafa_ekki_stofnud','faera_kt',
                                                   'gleymt','greitt_sidar','aud_sala','stadfesta_greidslu','annad')),
  solur_id         bigint references public.solur(id) on delete set null,
  customer_base_id bigint references public.customers_base(id) on delete set null,
  fyrirtaeki_id    bigint references public.fyrirtaeki(id) on delete set null,
  upphaed          numeric,
  stada            text not null default 'opid'
                   check (stada in ('opid','tilbuid_i_vinnslu','i_vinnslu','i_yfirferd_agnars','lokid','sleppt')),
  skref            jsonb not null default '{}'::jsonb,
  gogn             jsonb not null default '{}'::jsonb,
  athugasemd       text,
  saga             jsonb not null default '[]'::jsonb,
  uppfaert_af      text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists krofu_verkferli_solur_idx on public.krofu_verkferli (solur_id);
create index if not exists krofu_verkferli_stada_idx on public.krofu_verkferli (stada);

comment on table public.krofu_verkferli is 'Framvinda vinnuglugga krafna (369): eitt mál á röð. Vinnuglugginn sendir aldrei neitt; lokasending er Agnars.';
comment on column public.krofu_verkferli.mal_lykill is 'uppruni:id:tegund, t.d. solur:454:faera_kt · fyrirtaeki:1175:gleymt:2026 · solur:<id>:annad:<stimpill>';
comment on column public.krofu_verkferli.stada is 'opid → tilbuid_i_vinnslu (Agnar) → i_vinnslu (Claude) → i_yfirferd_agnars (ósend í Kröfuyfirliti) → lokid; eða sleppt';
comment on column public.krofu_verkferli.saga is 'Stöðubreytingar [{kl, fra, til, af}] — skrifað af gikknum krofu_verkferli_stimpill, aldrei af viðmótinu';

-- ── 2. Gikkur: updated_at + saga (viðbót, aldrei endurskrifuð) ───────────────────────────
create or replace function public.krofu_verkferli_stimpill()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  if tg_op = 'INSERT' then
    new.saga := pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
      'kl', pg_catalog.now(), 'fra', null, 'til', new.stada, 'af', new.uppfaert_af));
  else
    new.created_at := old.created_at;
    new.saga := coalesce(old.saga, '[]'::jsonb);
    if new.stada is distinct from old.stada then
      new.saga := new.saga || pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object(
        'kl', pg_catalog.now(), 'fra', old.stada, 'til', new.stada, 'af', new.uppfaert_af));
    end if;
  end if;
  return new;
end
$$;

drop trigger if exists krofu_verkferli_stimpill on public.krofu_verkferli;
create trigger krofu_verkferli_stimpill
  before insert or update on public.krofu_verkferli
  for each row execute function public.krofu_verkferli_stimpill();

-- ── 3. Aðgangur ──────────────────────────────────────────────────────────────────────────
alter table public.krofu_verkferli enable row level security;
revoke all on public.krofu_verkferli from anon, authenticated;
grant select, insert, update on public.krofu_verkferli to anon, authenticated;

drop policy if exists krofu_verkferli_lesa on public.krofu_verkferli;
create policy krofu_verkferli_lesa on public.krofu_verkferli for select to anon, authenticated using (true);
drop policy if exists krofu_verkferli_stofna on public.krofu_verkferli;
create policy krofu_verkferli_stofna on public.krofu_verkferli for insert to anon, authenticated with check (true);
drop policy if exists krofu_verkferli_uppfaera on public.krofu_verkferli;
create policy krofu_verkferli_uppfaera on public.krofu_verkferli for update to anon, authenticated using (true) with check (true);
-- Viljandi engin delete-regla.

-- ── 4. Upphafsmál (VALFRJÁLST — sleppa má þessum kafla) ──────────────────────────────────
-- 4a. Fjórir reikningar sendir 01.–03.07.2026 ÁN bankakröfu (Payday-útflutningur: „Krafa stofnuð" = Nei), allir ógreiddir.
--     Upphæðir, auðkenni og Payday-númer eru lesin úr gögnunum sjálfum, ekki slegin inn.
insert into public.krofu_verkferli (mal_lykill, tegund, solur_id, customer_base_id, fyrirtaeki_id, upphaed, stada, gogn, uppfaert_af)
select 'solur:' || s.id || ':krafa_ekki_stofnud', 'krafa_ekki_stofnud', s.id, s.customer_base_id, s.customer_id, s.samtals, 'opid',
       jsonb_build_object(
         'heimild', 'Payday-útflutningur 11.09.2026: „Krafa stofnuð" = Nei (sendur 01.–03.07.2026, ógreiddur)',
         'stofnad_i', 'sql 2026-09-11',
         'upphaflegt', jsonb_build_object('num', s.num, 'dk_invoice_id', s.dk_invoice_id, 'payday_nr', p.number,
           'customer_nafn', s.customer_nafn, 'customer_kt', s.customer_kt, 'customer_base_id', s.customer_base_id, 'customer_id', s.customer_id)),
       'sql 2026-09-11'
from public.solur s
left join public.payday_invoices_slokk p on p.payday_id = s.dk_invoice_id
where s.num in ('R-000431', 'R-000357', 'R-000356', 'R-000339')
  and s.paid_at is null and coalesce(s.status, '') <> 'void' and not coalesce(s.is_credit, false)
on conflict (mal_lykill) do nothing;

-- 4b. R-000406 Húsfélag Álftamýri 48 (solur 454, Payday nr. 20): greiðandi á að vera 570400-2070 (Álftamýri 46-52),
--     sem er EKKI til í customers_base (mælt 11.09.2026) → leiðin „stofna félag fyrst".
insert into public.krofu_verkferli (mal_lykill, tegund, solur_id, customer_base_id, fyrirtaeki_id, upphaed, stada, gogn, uppfaert_af)
select 'solur:' || s.id || ':faera_kt', 'faera_kt', s.id, s.customer_base_id, s.customer_id, s.samtals, 'opid',
       jsonb_build_object(
         'markkt', '5704002070',
         'marknafn', 'Álftamýri 46-52 (húsfélag)',
         'texti', 'Greiðandi á að vera húsfélagið Álftamýri 46-52 (570400-2070), ekki Álftamýri 48.',
         'stofnad_i', 'sql 2026-09-11',
         'upphaflegt', jsonb_build_object('num', s.num, 'dk_invoice_id', s.dk_invoice_id, 'payday_nr', p.number,
           'customer_nafn', s.customer_nafn, 'customer_kt', s.customer_kt, 'customer_base_id', s.customer_base_id, 'customer_id', s.customer_id)),
       'sql 2026-09-11'
from public.solur s
left join public.payday_invoices_slokk p on p.payday_id = s.dk_invoice_id
where s.id = 454 and s.num = 'R-000406' and s.paid_at is null
on conflict (mal_lykill) do nothing;

-- ── 5. Staðfesting eftir beitingu (lesið) ────────────────────────────────────────────────
-- select mal_lykill, tegund, stada, upphaed, gogn->>'markkt' markkt, jsonb_array_length(saga) saga from public.krofu_verkferli order by id;
--   → 5 raðir: 4 × krafa_ekki_stofnud (36.411 · 19.927 · 15.686 · 11.966) og solur:454:faera_kt (92.192), allar 'opid', saga = 1.
-- select relrowsecurity from pg_class where oid = 'public.krofu_verkferli'::regclass;                       → true
-- select string_agg(privilege_type, ',') from information_schema.role_table_grants
--   where table_schema = 'public' and table_name = 'krofu_verkferli' and grantee = 'anon';                  → INSERT,SELECT,UPDATE

-- ── 6. Tillaga síðar (EKKI hluti af þessu) ───────────────────────────────────────────────
-- Ef Payday-API sýnir hvort banka krafa var stofnuð, má payday-pull-slokk fylla dálk í speglinum og 369 flokka sjálft:
--   alter table public.payday_invoices_slokk add column if not exists krafa_stofnud boolean;   -- null = óþekkt
-- Þangað til er flaggið handvirkt mál í krofu_verkferli (kafli 4a eða „⚑ Krafa ekki stofnuð" í vinnuglugganum).

-- ── Afturköllun (aðeins ef hætta á við) ──────────────────────────────────────────────────
-- drop table if exists public.krofu_verkferli;
-- drop function if exists public.krofu_verkferli_stimpill();
